make:
	gcc -o main main.c Manager/timer.c Manager/timer.h Manager/cpu.c Manager/cpu.h Manager/executingState.c Manager/executingState.h Manager/blockedState.c Manager/blockedState.h Manager/ReadyState.c Manager/ReadyState.h Manager/ProcessTable.c Manager/ProcessTable.h Process.c Process.h control/controller.c control/controller.h Printer/Printer.c Printer/Printer.h Manager/manager.c Manager/manager.h -lm
run:
	./main